### ISSUE TITLE
We need some form of messaging notification

### ISSUE THREAD

**Issue by DinizCabreira** [mdom/smokesignal#1]
Perhaps a simple display of how many unread messages have been received since the last terminal log-in would suffice?

**Comment by mdom** [comment]
Thanks for the suggestion, but that sounds rather complicated for something that is quick fun project modeled after a web comic... :) But I would be happy to merge a pr if you want to try it. Maybe a stat subcommand that counts  the number of messages and compare it with the last count? But what to do with rotated logs?
